rules:
  #https://github.com/Dreamacro/clash/wiki/Configuration#:~:text=tls%0A%20%20%0A%20%20%23%20%E2%80%A6%E2%80%A6-,Rules,-Available%20keywords%3A
  # - IP-CIDR,127.0.0.0/8,DIRECT
  #- SRC-IP-CIDR,192.168.1.201/32,DIRECT
  #- RULE-SET,Special,DIRECT
  #- GEOIP,CN,Domestic

  #vPeer
  - IP-CIDR,67.230.178.193/32,DIRECT
  - IP-CIDR,4.193.135.33/32,DIRECT
  - IP-CIDR,4.193.54.245/32,DIRECT


    # ChatGPT
  - RULE-SET,speedtest,ChatGPT
  - RULE-SET,openai,ChatGPT
  - RULE-SET,claude,ChatGPT
  - RULE-SET,gemini,ChatGPT
  - RULE-SET,bing,ChatGPT

  
  - RULE-SET,private,DIRECT
  - RULE-SET,direct,DIRECT
  - RULE-SET,lancidr,DIRECT
  - RULE-SET,cncidr,DIRECT
  - GEOIP,LAN,DIRECT
  - GEOIP,CN,DIRECT
#   #远程ToDesk远程软件
#   - PROCESS-NAME,ToDesk.exe,DIRECT
#   #远程桌面
#   - PROCESS-NAME,mstsc.exe,DIRECT
#   #蓝叠
#   - PROCESS-NAME,BstkSVC.exe,PROXY
#   - PROCESS-NAME,HD-Player.exe,PROXY
#   #浏览器
#   - PROCESS-NAME,chrome0.exe,DIRECT
#   - PROCESS-NAME,chrome1.exe,PROXY1
#   - PROCESS-NAME,chrome2.exe,PROXY2
#   - PROCESS-NAME,chrome3.exe,PROXY3
#   - PROCESS-NAME,msedge1.exe,PROXY1
#   - PROCESS-NAME,msedge2.exe,PROXY2
#   - PROCESS-NAME,firefox1.exe,PROXY1
#   - PROCESS-NAME,firefox2.exe,PROXY2
#   #绿色版火狐
#   - PROCESS-NAME,phyrox-portable1.exe,PROXY1
#   - PROCESS-NAME,phyrox-portable2.exe,PROXY2
#   #海外聊天软件
#   - PROCESS-NAME,Discord.exe,PROXY
#   - PROCESS-NAME,Telegram.exe,PROXY
#   #OneDrive
#   - PROCESS-NAME,OneDrive.exe,PROXY
#   #windows命令行终端
#   - PROCESS-NAME,WindowsTerminal.exe,dev
#   - PROCESS-NAME,OpenConsole.exe,dev
#   - PROCESS-NAME,powershell.exe,dev
#   # - PROCESS-NAME,cmd.exe,dev
#   # - PROCESS-NAME,conhost.exe,dev
#   - PROCESS-NAME,Code.exe,dev
#   - PROCESS-NAME,git.exe,dev
#   - PROCESS-NAME,git-remote-https.exe,dev
  # 自定义规则组
  # - DOMAIN,ipinfo.io,IPtest

  

  # - DOMAIN-SUFFIX,openai.com,PROXY
  # - DOMAIN-SUFFIX,cloudflare.com,PROXY
  # - DOMAIN-SUFFIX,sentry.com,PROXY

  # bing


  # telegram
  # - RULE-SET,telegram,PROXY
  - RULE-SET,telegramcidr,PROXY
  - RULE-SET,telegram_sg,PROXY


  #https://github.com/Loyalsoldier/clash-rules
  #白名单模式
  # - RULE-SET,applications,DIRECT
  # - DOMAIN,clash.razord.top,DIRECT
  # - DOMAIN,yacd.haishan.me,DIRECT
  - RULE-SET,reject,REJECT
  - RULE-SET,icloud,DIRECT
  - RULE-SET,apple,DIRECT
  - RULE-SET,google,PROXY
  - RULE-SET,proxy,PROXY
  - MATCH,PROXY
