mode: Rule
log-level: silent
allow-lan: true
bind-address: "*"
port: 3456
socks-port: 3457
mixed-port: 3458
redir-port: 3459
# ui source : https://github.com/MetaCubeX/Yacd-meta/archive/gh-pages.zip
# external-controller: '0.0.0.0:3450'
# external-ui: ui
secret: ''


cfw-latency-url: http://cp.cloudflare.com/generate_204
cfw-latency-timeout: 3000
cfw-latency-type: 1
cfw-conn-break-strategy: true


clash-for-android:
  ui-subtitle-pattern: '[一-龥]{2,4}'
experimental:
  ignore-resolve-fail: true
tun:
   enable: true
   stack: system
auto-redir:
    enable: true
    auto-route: true
url-rewrite:
- ^https?:\\/\\/(www.)?(g|google)\\.cn https://www.google.com 302
- ^https?:\\/\\/(ditu|maps).google\\.cn https://maps.google.com 302


dns:
  enable: true
  # ipv6: false
  listen: 0.0.0.0:53
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  
  # 仅填写 DNS 服务器的 IP 地址，填写的 DNS 服务器将会被用来解析 nameserver 服务的域名
  default-nameserver:
    - 202.96.134.133
    
  # 自定义DNS将添加在下方并优先使用 支持Doh/Dot等dns
  # 支持 UDP / TCP / DoT / DoH 协议的 DNS 服务，可以指明具体的连接端口号
  # 所有 DNS 请求将会直接发送到服务器，不经过任何代理
  # Clash 会使用最先获得的解析记录回复 DNS 请求
  nameserver:
    - https://223.5.5.5/dns-query
    - https://1.12.12.12/dns-query
    #- https://doh.pub/dns-query
    #- https://dns.alidns.com/dns-query

  fallback:
    - tls://8.8.8.8:853
    - tls://1.1.1.1:853

  # https://github.com/vernesong/OpenClash/blob/master/luci-app-openclash/root/etc/openclash/custom/openclash_custom_fallback_filter.yaml
  # If IP addresses resolved with servers in `nameservers` are in the specified
  # subnets below, they are considered invalid and results from `fallback`
  # servers are used instead.
  #
  # IP address resolved with servers in `nameserver` is used when
  # `fallback-filter.geoip` is true and when GEOIP of the IP address is `CN`.
  #
  # If `fallback-filter.geoip` is false, results from `nameserver` nameservers
  # are always used if not match `fallback-filter.ipcidr`.
  #
  # This is a countermeasure against DNS pollution attacks.
  fallback-filter:
    geoip: true
    geoip-code: CN
    # ipcidr:
    #   - 0.0.0.0/8
    #   - 10.0.0.0/8
    #   - 100.64.0.0/10
    #   - 127.0.0.0/8
    #   - 169.254.0.0/16
    #   - 172.16.0.0/12
    #   - 192.0.0.0/24
    #   - 192.0.2.0/24
    #   - 192.88.99.0/24
    #   - 192.168.0.0/16
    #   - 198.18.0.0/15
    #   - 198.51.100.0/24
    #   - 203.0.113.0/24
    #   - 224.0.0.0/4
    #   - 240.0.0.0/4
    #   - 255.255.255.255/32
    domain:
      - "+.google.com"
      - "+.facebook.com"
      - "+.youtube.com"
      - "+.githubusercontent.com"
      - "+.googlevideo.com"
      - "+.msftconnecttest.com"
      - "+.msftncsi.com"

